apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplemathoperationsapi
  namespace: simplemathoperationsapi
spec:
  selector:
    matchLabels:
      app: simplemathoperationsapi
  template:
    metadata:
      labels:
        app: simplemathoperationsapi
    spec:
      containers:
      - name: simplemathoperationsapi-container
        image: simplemathoperationsapi:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Development"