apiVersion: v1
kind: Service
metadata:
  name: simplemathoperationsapi-service
  namespace: simplemathoperationsapi
spec:
  selector:
    app: simplemathoperationsapi
  ports:
  - port: 8080
    targetPort: 80
  type: LoadBalancer